# Generated by Django 6.0.3 on 2026-03-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0002_chatroomreadstate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
    ]
