# Generated by Django 6.0.3 on 2026-04-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0004_alter_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='chat_group_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='group_images'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
